### ISSUE TITLE
FEATURE: Add Twitter

### ISSUE THREAD

**Issue by molinto** [incandenza-11/blockout2024#3]
Using https://pypi.org/project/twitter-api-client/0.10.22/ to interact with the Twitter accounts.

I'll help out asap.

**Comment by sandrasgg** [comment]
Thanks a lot @molinto, adding Twitter would be great. 🚀 I'm assigning this to you, let me know if you need help 😄

**Comment by infinite-wait** [comment]
hey @molinto have you started with this one? If not, I can start working on it :)

**Comment by molinto** [comment]
Hi, apologies for the delay. I tried earlier in the week but Python isn't my strong point.

**Comment by infinite-wait** [comment]
@molinto No worries, I'll start working on this one

**Comment by fkblackrock** [comment]
@incandenza-11 do you want me to contribute to the twitter branch? Do you plan on doing something the next 5 days?
